'1':
- user:
    clan_name: 样例：公会名字
    group_id: 样例：qq群号
'2':
- user:
    clan_name: 样例：公会名字
    group_id: 样例：qq群号
'3':
- user:
    clan_name: 样例：公会名字
    group_id: 样例：qq群号
'4':
- user:
    clan_name: 样例：公会名字
    group_id: 样例：qq群号
